services:
  oracle:
    image: gvenzl/oracle-free:23-slim
    container_name: oracle-free
    environment:
      ORACLE_PASSWORD: Oracle123
      APP_USER: app
      APP_USER_PASSWORD: app123
      ORACLE_CHARACTERSET: AL32UTF8
      ORACLE_DATABASE: TEXTILAB
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
