services:
  oracle19c:
    image: oracle/database:19.3.0-ee
    container_name: oracle-19c
    environment:
      ORACLE_SID: TEXTILAB
      ORACLE_PDB: TEXTILABPDB
      ORACLE_PWD: Oracle123
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./oracle/scripts/setup:/opt/oracle/scripts/setup
    shm_size: "2g"

volumes:
  oracle-data:
